### ISSUE TITLE
Example url endpoint not found

### ISSUE THREAD

**Issue by josago97** [openvisionapi/ova-server#1]
Hello, I have tried to test the service with the available url (https://api.openvisionapi.com/api/v1/detection) but it always returns an error saying that the endpoint is not found.

Thank you.

**Comment by pythops** [comment]
Hi @josago97 
Yes, I don't have the demo instance running for the moment. Probably it's gonna be up in couple of weeks. 
Meanwhile, you need to run the ova-server locally if you want to try it
